package main

import (
	"rms/db"
	_ "rms/docs" // docs is generated by Swag CLI, you have to import it.
	"rms/handler"
	"rms/router"

	echoSwagger "github.com/swaggo/echo-swagger" // echo-swagger middleware
)

func main() {

	r := router.New()

	r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")
	db.InitDatabase()
	db := db.DBConn

	h := handler.NewHandler(db)
	h.Register(v1)
	r.Logger.Fatal(r.Start(":8588"))

}
